apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-deployment-priv
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause  
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause
        securityContext:
          privileged: true
