kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "{{INSTALL_DIR}}/certs/ca.pem"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "{{CLUSTER_DNS}}"
RuntimeRequestTimeout: "15m"
tlsCertFile: "{{INSTALL_DIR}}/certs/{{HOSTNAME}}-kubelet.pem"
tlsPrivateKeyFile: "{{INSTALL_DIR}}/certs/{{HOSTNAME}}-kubelet-key.pem"
