kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
  - resources:
      - secrets
    providers:
    - identity: {}
    - aescbc:
        keys:
        - name: key1
          secret: {{ key }}
