apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v{{kubernetes_version}}
controlPlaneEndpoint: {{api_server_loadbalancer_hostport}}
networking:
  serviceSubnet: {{service_subnet}}
  podSubnet: {{pod_subnet}}
